#存放sit、uat、ver多环境域名、账号密码、接口地址、请求参数，实现命令行一键切换测试环境
[sit]
url = https://www.saucedemo.com/
login_url = https://jsonplaceholder.typicode.com/users
data = {"email": "renyuqiao@3333","password": "3333","token":"Header.Payload.Signature"}
username = standard_user
passwd = secret_sauce
tag = sit


[uat]
url = https://www.saucedemo.com/
login_url = https://jsonplaceholder.typicode.com/users
data = {"email": "renyuqiao@3333","password": "3333","token":"Header.Payload.Signature"}
username = standard_user
passwd = secret_sauce
tag = uat

[ver]
url = https://www.saucedemo.com/
login_url = https://jsonplaceholder.typicode.com/users
data = {"email": "renyuqiao@3333","password": "3333","token":"Header.Payload.Signature"}
username = standard_user
passwd = secret_sauce
tag = ver